In [1]:
import os
import numpy
import gymnasium as gym
import matplotlib.pyplot as plt
import random
import numpy as np

In [10]:
env=gym.make('FrozenLake-v1')
for state in env.P:
    print(state)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [11]:
for a in env.P[state]:
    print(a)

0
1
2
3


In [265]:
class Policy_Iteration:
    def __init__(self,gamma,env,theta):
        self.gamma=gamma
        self.env=env
        self.V=np.zeros(self.env.observation_space.n)
        self.theta=theta  
        
        self.pi =(1/env.action_space.n)*np.ones((self.env.observation_space.n,self.env.action_space.n))
    def policy_iteration(self):
        
        delta=0
        d=np.zeros((self.env.observation_space.n,self.env.action_space.n))
       
        while delta<self.theta:
            a=np.zeros(self.env.observation_space.n)
            for state in self.env.P:
                v=self.V[state].copy()
                for action in self.env.P[state]:
                    
                    for prob,next_state,reward,terminated in env.P[state][action]:
                        d[state][action]+=prob*(reward+self.gamma*self.V[next_state])
                    a[state]+=self.pi[state][action]*d[state][action]
                self.V[state]=a[state].copy()
                  
                delta=max(delta,abs(self.V[state]-v))
                   
    def policy_improvement(self):
        
        policy_stable=True
        q=np.zeros((self.env.observation_space.n,self.env.action_space.n))
        for state in self.env.P:
            old_pi=self.pi[state].copy()   
            for action in self.env.P[state]:
                for prob,next_state,reward,terminated in self.env.P[state][action]:
                    q[state][action]+=prob*(reward+self.gamma*self.V[next_state])
            best_actions=np.where(q[state]==np.max(q[state]))
            self.pi[state]=np.zeros(self.env.action_space.n)
            self.pi[state , best_actions]=1/np.size(best_actions)
            print('old_pi: ',old_pi)
            print('pi :',self.pi[state])
            
            if(np.allclose(self.pi[state],old_pi)):
                policy_stable=False
       
        if not policy_stable:
            self.policy_iteration()
    def test(self,eps,env):
        for i in range(eps):
            done=False
            state,_=env.reset()
            action=np.random.choice(np.where(self.pi[state]==np.max(self.pi[state])[0]))
            env.render()
            while not done:
                new_state,reward,terminated,_,_=env.step(action)
                action=np.random.choice(np.where(self.pi[new_state]==np.max(self.pi[new_state]))[0])
                state=new_state
                done=terminated
        env.close()
    
            
                
                
                
            
                    
      

In [270]:
model=Policy_Iteration(0.9,env,0.000000001)
model.policy_iteration()
print(model.V)
model.policy_improvement()

[0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.25 0.  ]
old_pi:  [0.25 0.25 0.25 0.25]
pi : [0.25 0.25 0.25 0.25]
old_pi:  [0.25 0.25 0.25 0.25]
pi : [0.25 0.25 0.25 0.25]
old_pi:  [0.25 0.25 0.25 0.25]
pi : [0.25 0.25 0.25 0.25]
old_pi:  [0.25 0.25 0.25 0.25]
pi : [0.25 0.25 0.25 0.25]
old_pi:  [0.25 0.25 0.25 0.25]
pi : [0.25 0.25 0.25 0.25]
old_pi:  [0.25 0.25 0.25 0.25]
pi : [0.25 0.25 0.25 0.25]
old_pi:  [0.25 0.25 0.25 0.25]
pi : [0.25 0.25 0.25 0.25]
old_pi:  [0.25 0.25 0.25 0.25]
pi : [0.25 0.25 0.25 0.25]
old_pi:  [0.25 0.25 0.25 0.25]
pi : [0.25 0.25 0.25 0.25]
old_pi:  [0.25 0.25 0.25 0.25]
pi : [0.25 0.25 0.25 0.25]
old_pi:  [0.25 0.25 0.25 0.25]
pi : [0. 1. 0. 0.]
old_pi:  [0.25 0.25 0.25 0.25]
pi : [0.25 0.25 0.25 0.25]
old_pi:  [0.25 0.25 0.25 0.25]
pi : [0.25 0.25 0.25 0.25]
old_pi:  [0.25 0.25 0.25 0.25]
pi : [0. 0. 1. 0.]
old_pi:  [0.25 0.25 0.25 0.25]
pi : [0. 0. 1. 0.]
old_pi:  [0.25 0.25 0.25 0.25]
pi : [0.25 0.25 0.25 0.25]


In [244]:
env=gym.make('FrozenLake-v1', desc=None, map_name="4x4", is_slippery=False,render_mode='human')
# model.test(5,env)


In [256]:
model.V

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.])

In [172]:
best_actions=np.where(model.q[10]==np.max(model.q[10]))

In [216]:
a=model.pi

In [218]:
a[0][1]=1

In [219]:
a

array([[0.  , 1.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  ],
       [0.25, 0.25, 0.25, 0.25]])

In [269]:
model.pi

array([[0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.  , 1.  , 0.  , 0.  ],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.  , 0.  , 1.  , 0.  ],
       [0.  , 0.  , 1.  , 0.  ],
       [0.25, 0.25, 0.25, 0.25]])